version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "rehype-*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "remark-*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "unified"
        update-types: ["version-update:semver-major"]
      - dependency-name: "remark-emoji"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
