apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: xlog
  namespace: crossbell
spec:
  maxReplicas: 11
  minReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xlog
  targetCPUUtilizationPercentage: 70
